### ISSUE TITLE
Incorrect coloring/filtering with paragliding values

### ISSUE THREAD

**Issue by elgandoz** [philseeley/wheretofly_app#1]
**OS**: Android (10), but likely iOS as well
**Affected version**: 6.6.0
**Latest known working version**: 6.4.0

After the latest update on the Google Play Store, the app does no longer display the correct values when the "Show Paragliding Values" option is on.

All arrows appear grey despite direction and strength are "good". Therefore with the filter for "On" sites, nothing appears.

When the paragliding value is off, it seems to work as expected.

Tested on 2 different phones.

## Screenshots:
| WTF 6.4.0 Android _(previous version)_  | WTF 6.6.0 Android _(current version)_ |
| ------------- | ------------- |
|<img src="https://user-images.githubusercontent.com/5859926/91385929-42ef0600-e875-11ea-8980-de992000abde.png" alt="WTF 6.4.0 Android" height="500">|<img src="https://user-images.githubusercontent.com/5859926/91386027-76319500-e875-11ea-99fc-6757ffa4ef02.png" alt="WTF 6.6.0 Android" height="500">|

**Comment by philseeley** [comment]
The error was introduced in [this](https://github.com/philseeley/wheretoflyapp/commit/210408d4bb9c2c02e4e139433dcc6be48d1be59c) commit.

**Comment by philseeley** [comment]
Fixed in [this](https://github.com/philseeley/wheretofly/commit/9ef8975577d81e33d71225cf45b3d2fe82feedea) commit and published.
